# Generated by Django 5.0.3 on 2024-04-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_singleorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleOrder',
        ),
    ]
